---
platforms:
  - name: "lex-incus-libvirt-${MOLECULE_RUN_ID:-local}"
    image: https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2
    image_checksum: sha256:https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2.sha256
