---
galaxy_info:
  author: jedimasterjonny
  description: Developer and Ansible-author tooling for Lex Imperialis lab hosts.
  license: GPL-3.0-or-later
  min_ansible_version: "2.19"
  galaxy_tags:
    - homelab
    - suse
    - dev
dependencies:
  - role: jedimasterjonny.lex.common
