---
- name: Converge
  hosts: all
  tasks:
    - name: Apply the podman role
      ansible.builtin.include_role:
        name: podman

    - name: Apply the node_exporter role
      ansible.builtin.include_role:
        name: node_exporter
