disabled = false
locale = "en"
label = "English"
weight = 1
title = "jonnyoc.uk"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

 [params.author]
   name = "Jonny O'Connell"
   image = "img/avatar.jpg"
   imageQuality = 96
   headline = "Purveyor of questionable commits"
   links = [
      { github = "https://github.com/jedimasterjonny" },
      { linkedin = "https://linkedin.com/in/jonnyoconnell" },
   ]
