---
namespace: jedimasterjonny
name: lex
version: 0.3.0
readme: README.md
authors:
  - jedimasterjonny <46541898+jedimasterjonny@users.noreply.github.com>
description: Lex Imperialis - Ansible roles for a SUSE-based home lab.
license:
  - GPL-3.0-or-later
tags:
  - infrastructure
  - linux
  - homelab
  - suse
  - tumbleweed
dependencies:
  ansible.posix: ">=2.2.0"
  community.general: ">=13.0.0"
  community.libvirt: ">=2.2.0"
repository: https://github.com/jedimasterjonny/lex-imperialis
issues: https://github.com/jedimasterjonny/lex-imperialis/issues
build_ignore:
  - "*.tar.gz"
  - .molecule
  - molecule
  - roles/*/molecule
