---
- name: Reload NetworkManager for incus
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: reloaded
  become: true

- name: Reload systemd for incus
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
