---
- name: Configure solar
  hosts: solar
  roles:
    - common
    - sshd
    - firewalld
    - podman
    - autoupdate
    - nfs
    - caddy
    - grafana
    - homepage
    - arr
    - podman_backup
    - home_backup
    - node_exporter
    - cadvisor
    - alertmanager
